;3.22
(define (make-queue-proc)
  (let ((front-ptr '())
         (rear-ptr '()))
    (define (empty-queue?)
      (null? front-ptr))
    (define (print-queue)
      front-ptr)
    (define (insert-queue! item)
      (let ((new-pair (cons item '())))
        (cond ((empty-queue?)
                (set! front-ptr new-pair)
                (set! rear-ptr new-pair)
                'ok)
          (else
            (set-cdr! rear-ptr new-pair)
            (set! rear-ptr new-pair)
            'ok)))
      )
    (define (delete-queue!)
      (cond
        ((empty-queue?) (error "Trying to delete on an empty queue!"))
        (else
          (set! front-ptr (cdr front-ptr))
              ))
      )
    (define (dispatch m)
      (cond
        ((eq? m 'insert-queue!) insert-queue!)
        ((eq? m 'print-queue) print-queue)
        ((eq? m 'delete-queue!) delete-queue!)
        ))
    dispatch))

(define (insert-queue! queue item)
  ((queue 'insert-queue!) item))
(define (delete-queue! queue)
  ((queue 'delete-queue!)))
(define (print-queue queue)
  ((queue 'print-queue)))

; Testing
(define Q (make-queue-proc))
(insert-queue! Q 'a)
(print-queue Q);Expected: (a)
(insert-queue! Q 'b)
(print-queue Q);Expected: (a b)
(insert-queue! Q 'c)
(print-queue Q);Expected: (a b c)
(delete-queue! Q)
(print-queue Q);Expected: (b c)
